### ISSUE TITLE
Readme bug: markdown headers not rendering correctly

### ISSUE THREAD

**Issue by biblicalph** [koficodes/make-or-fix#3]
### Issue CheckList
- [x] Your issue has been labeled with the respective type

### Issue Summary
The readme headers are not displaying correctly. Instead of displaying headers, it is displaying the markdown value. Example ##Setup should display as header but it doesn't.

### Expected Behaviour
##Setup ##License should display as headers

### Actual Behaviour
The display the markdown value

### Steps to Reproduce (bugs only)
n/a

### Other Technical details if Needed ?
n/a

**Comment by paulkarikari** [comment]
fixed it with #4
